spring.application.name=jpaTutorial

# Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/product_database
spring.datasource.username=sathwik
spring.datasource.password=YOUR_PASSWORD

#allow using data.sql
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true