spring.application.name=webtutorial
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=employeeDb
spring.datasource.password=1234